# set the results_folder to the place that you would like results to be saved
results_folder: "/Users/joshl/PycharmProjects/ARS/Results/"

# Set this to the location of your alignment reference file for the aligner tool you are using (guppy/minimap/vsearch)
alignment_reference_file: "/Users/joshl/PycharmProjects/ARS/Results/DataFiles/zymogen_alignment_reference.fasta"

# ORIENT/TRIMMING CONFIG (cutadapt)
trim_error_rate: 0.15
trim_three_prime_adapter: ACTTGCCTGTCGCTCTATCTTCTACCTTGTTACGACTT
trim_five_prime_adapter: TTTCTGTTGGTGCTGATATTGCAGRGTTYGATYMTGGCTCAG

# VSEARCH ALIGNER
# The match rate is a percentage of each read that must be matched before it is classified
#   Raising this value gives fewer results that are matched more closely
#   Lowering this value gives more results that are not as closely matched
vsearch_match_rate: 0.90
