POST_TRIM_FOLDER_NAMES = os.listdir("/Users/joshl/Documents/Trim")


rule test:
    input:
        files = expand("/Users/joshl/Documents/Trim/{barcode_number}/{barcode_number}.merged.trimmed.fastq", barcode_number=POST_TRIM_FOLDER_NAMES)
    output:
        "/Users/joshl/Desktop/outputfile.txt"
    params:
        barcode_number = lambda wildcards: "{barcode_number}",
        bar = "{barcode_number}"
    log:
        "/Users/joshl/Desktop/logs.log"
    message: "This is a message"
    shell:
        "echo {params.barcode_number}"